name: GitHub Actions Demo
run-name: GitHub Actions Workflow new 25🚀
on: 
 push:
   branches:
     - main
   
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Make runner busy
        run: 
          | 
            #echo "Runner Sleeping...."
            #sleep 50
            x=10

            while true
            do
            echo "Runner is sleeping"
            sleep 2
            echo $x
            if [ $x -gt 20 ]
            then
            break
            ((x--))
            fi
            done
            
            
        
