name: GitHub Protected push
run-name: GitHub Actions Workflow new 23🚀
on: 
 push:
   branches:
     - main
   
jobs:
  Explore-GitHub-Actions:
    runs-on: Windows-latest
    steps:
      - name: Make runner busy
        run: 
          | 
            echo "Runner Sleeping...."
            #sleep 50
